<?php

// Définir les routes de l'application
$routes = [
    URL . '/' => ['HomeController', 'index'],
    URL . '/connexion' => ['ConnexionController', 'index'],
    URL . '/home' => ['HomeConnectedController', 'index'],
    URL . '/deconnexion' => ['DeconnexionController', 'index'],
    URL . '/projets' => ['ProjetsController', 'index'],
    URL . '/projets/list' => ['ProjetsController', 'list'],
    URL . '/projets/add' => ['ProjetsController', 'ajouter'],
    URL . '/projets/edit' => ['ProjetsController', 'modifier'],
    URL . '/projets/delete' => ['ProjetsController', 'supprimer'],
    URL . '/formations' => ['FormationsController', 'index'],
    URL . '/entreprises' => ['EntreprisesController', 'index'],
    URL . '/campus' => ['CampusController', 'index'],
    URL . '/alternances' => ['AlternancesController', 'index'],
    URL . '/offres' => ['AlternancesController', 'list'],
    URL . '/offres/add' => ['AlternancesController', 'ajouter'],
    URL . '/offres/edit' => ['AlternancesController', 'modifier'],
    URL . '/offres/delete' => ['AlternancesController', 'supprimer'],
    URL . '/notes' => ['NotesController', 'index'],
    URL . '/notes/edit' => ['NotesController', 'modifier'],
    URL . '/notes/add' => ['NotesController', 'ajouter'],
    URL . '/notes/delete' => ['NotesController', 'supprimer'],
    URL . '/inscription' => ['InscriptionController', 'index'],
    URL . '/emplois-du-temps' => ['EDTController', 'index'],
    URL . '/emplois-du-temps/add' => ['EDTController', 'ajouter'],
    URL . '/emplois-du-temps/delete' => ['EDTController', 'supprimer'],
    URL . '/rgpd' => ['RGPDController', 'index'],
    URL . '/users' => ['UsersController', 'index'],
    URL . '/users/add' => ['UsersController', 'ajouter'],
    URL . '/users/add/etudiant' => ['UsersController', 'ajouterEtudiant'],
    URL . '/users/add/entreprise' => ['UsersController', 'ajouterEntreprise'],
    URL . '/users/add/enseignant' => ['UsersController', 'ajouterEnseignant'],
    URL . '/users/add/administrateur' => ['UsersController', 'ajouterAdministrateur'],
    URL . '/users/edit/entreprise' => ['UsersController', 'editEntreprise'],
    URL . '/users/edit/etudiant' => ['UsersController', 'editEtudiant'],
    URL . '/users/edit/enseignant' => ['UsersController', 'editEnseignant'],
    URL . '/users/edit/administrateur' => ['UsersController', 'editAdministrateur'],
    URL . '/users/list' => ['UsersController', 'list'],
    URL . '/users/list/etudiant' => ['UsersController', 'listEtudiant'],
    URL . '/users/list/entreprise' => ['UsersController', 'listEntreprise'],
    URL . '/users/list/enseignant' => ['UsersController', 'listEnseignant'],
    URL . '/users/list/administrateur' => ['UsersController', 'listAdministrateur'],
    URL . '/users/list/entreprise/confirme' => ['UsersController', 'confirmeEntreprise'],
    URL . '/supports' => ['SupportsController', 'index'],
    URL . '/supports/add' => ['SupportsController', 'ajouter'],
    URL . '/supports/delete' => ['SupportsController', 'supprimer'],
    // Ajoutez d'autres routes selon vos besoins
];
